language: java
jdk:
  - openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B

notifications:
  email:
    recipients:
      - bricenemadjeu@gmail.com
      - romaricagwa10@gmail.com
      - yoandjimkouo@yahoo.com
      - arlettewamba@gmail.com
      - audreyjbea@gmail.com
    on_success: always
    on_failure: never

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: "GuNc+1BlIWTOxneSEq7LgYwbDUoGOmuTZhnpTToUPokXsm9tO2AIEx9nagt1ZFKGNAUEB50vncpWkawENt/LPN3tePCGn2OXUzc5Azmrt10v0PB7N46w9BNyi9T3k1STS83Z8cM1wYfjQV9f4l0NNsjxpYYZvnTqU5mrjC1DxNhLGl4pJ/fM6vwhJNcpy/pVOef8EaFuO5nUinaAV7jR0PYyo3eHnQBPN8nXY71LvZAf+aTyCqBAeIyVidftNtoD9eRCAvtzz1cUZGLhIy53//lxC0vQo4peHkMNd3b8KYsXKGDC2kw9/Nqr1jWdrvhis0t8iclUJKtA2arULmgW2ssp27D1DPQUriAJwOMZILdKPRCdYDedTCVoG/DwsvckgqEqd0idxcTitPNClwALOoN1m5r3OufQghU37SXKk1vASGLanrVQKFluFdvYgfdmIej9RId5DhcPphWF8lIbhxRuS0VX9XaZprU1pXUkqbroUu8ojNAYObzcxkiS73SFPg8Qgq2Hnou9iEduis2RGNGNyO7i05OmErKDu3zdIlFLSXia615WOt5oRgss1htf4I48kzjXJCDVU0LDRRtE8KZwhihtuhcCjfY8BgOJFtA5ehMTlYH8Swf3q/rz1dqxPU2iW+BhfqxTZR6U2g89FIlOdjM498iTPWg7LjWNMQ8="
  app: travis-projet
  on:
    branch: master
