language: java
jdk:
  - openjdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test -B

notifications:
  email:
    recipients:
      - bricenemadjeu@gmail.com
      - romaricagwa10@gmail.com
      - yoandjimkouo@yahoo.com
      - arlettewamba@gmail.com
      - audreyjbea@gmail.com
    on_success: always
    on_failure: never

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: "JQwH4TplFnI/rj7eBStQcpnrJL4XbJWJuu+ywmh8wROwxEbyjZ0ZgglAZlNaJqGA2kcs3PsQnPSVsKN4BjevtYItHsi/TcDMg2SFGtw/c5CHES/mfGNephZtNPTeeYtN+TtIRI7OctdPIbkNFXrHf2JUls08QbaDFlN9jm9bn6R+Z5h6YlbDYr4qIv3ZesPZg2Xrkx4rUvQeubq2oZ6xrIReVxXwj+WSLaIzp29wdCQlokL8XMPcMuaOVFFZDFlRF+A9VjS1l69bTYm15ZAUEF7+xGQ9PV3iFAbLMlmD2wIO3aIo1z1yvuNu/bjyGB92UmVvpQCr6XYma+ot92bteDqenCkEx04/jG0EzynQQhF/jATAxpT4LS6yBPSGkRA8zcGk/r6mLkCqUU6BadzOr7QCQfs2PhAXvQnZFkiiN3IYYhCczwqCMvDVOt/bXShDQN5kKbGwpawTfJJHzYQw/oS6kDEHeSfSaPxtXfRtLlCKv/lpCD/eFHHlbE7NGvmATGuBLcb7wWcXe+CduUrG6grfqZOun2067IKCyc4YwnGuSMMB99Dlvms0swI3Tik5CS9CH8ariYvIOCl9Ev03maMSj5VL+tdRltC5PEgoapZETfaO/pEjGrf3nBc5MskCKyCO3+/vEAeeNPeg6qKf6R9ascMqSXSSInpl1uWkGCI="
  app: travis-projet
  on:
    branch: master
